name: "CI shellcheck"
on:
  pull_request:
    paths:
      - ".github/workflows/shellcheck.yml"
      - ".github/scripts/**.sh"
  push:
    paths:
      - ".github/workflows/shellcheck.yml"
      - ".github/scripts/**.sh"

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: ".github/scripts"
      - run: .github/scripts/shellcheck.sh
