name: "CI Workflow Scan"
on:
  pull_request:
    paths:
      - ".github/workflows/**.ya?ml"
  push:
    paths:
      - ".github/workflows/**.ya?ml"

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: ".github/workflows"
      - uses: rcowsill/workflow-scan-action@v3
